---
language: python
sudo: required

services:
  - docker

env:
  - OS_VERSION=7
  - OS_VERSION=6

before_install:
  - sudo docker pull centos:${OS_VERSION}

install:
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/yum-plugin-priorities:ro --name centos-${OS_VERSION} centos:${OS_VERSION} sleep 300
  - sudo docker exec centos-${OS_VERSION} yum -y install epel-release
  - sudo docker exec centos-${OS_VERSION} yum -y install ansible
  - sudo docker exec centos-${OS_VERSION} rm /etc/ansible/ansible.cfg
  - sudo docker exec centos-${OS_VERSION} echo "[defaults]" > ansible.cfg
  - sudo docker exec centos-${OS_VERSION} echo "roles_path = /etc/ansible/roles/yum-plugin-priorites/" >> ansible.cfg
  - sudo docker exec centos-${OS_VERSION} pwd
  - sudo docker exec centos-${OS_VERSION} find / -name "*.cfg"
  - sudo docker exec centos-${OS_VERSION} find / -name "*.cfg.j2"

script:
#  - sudo docker exec centos-${OS_VERSION}  echo '[defaults]'; echo 'roles_path = /etc/ansible/roles/yum-plugin-priorites'; } >> ansible.cfg
  # Check syntax of ansible playbook
  - sudo docker exec centos-${OS_VERSION} ansible-playbook -i /etc/ansible/roles/yum-plugin-priorities/tests/inventory /etc/ansible/roles/yum-plugin-priorities/tests/test.yml --syntax-check
  # Run ansible playbook
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/yum-plugin-priorities/tests/test.yml

after_script:
  - sudo docker stop centos-${OS_VERSION}

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
